name: Update pkg.go.dev cache
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to refresh (e.g., v1.2.3 or module/v1.2.3)'
        required: true
        type: string

  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag || github.ref_name }}
    steps:
      - name: Warm pkg.go.dev cache
        run: curl https://proxy.golang.org/github.com/marknefedov/go-webpush/@v/${{ env.TAG }}.info